<?php

/** @noinspection SpellCheckingInspection */

namespace dface\Payment\LiqPay;

return [

	'MerchantAuthParams' => [
		'public_key' => ['type' => 'string', 'default' => null],
		'private_key' => ['type' => 'string', 'default' => null],
	],

	'PaymentRequest' => [
		'action' => ['type' => 'string', 'with' => true],
		'amount' => ['type' => 'float', 'with' => true],
		'currency' => ['type' => 'string', 'with' => true],
		'description' => ['type' => 'string', 'with' => true],
		'order_id' => ['type' => 'string', 'with' => true],
		'language' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'ip' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'expired_date' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'pay_types' => [
			'type' => 'string', 'default' => null, 'silent' => true, 'with' => true,
			'read_as'=> 'paytypes', 'write_as'=> 'paytypes',
		],
		'recurring_by_token' => [
			'type' => 'string', 'default' => null, 'silent' => true, 'with' => true,
			'read_as'=> 'recurringbytoken', 'write_as'=> 'recurringbytoken',
		],
		'server_url' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'verify_code' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'verifycode', 'write_as'=> 'verifycode',
		],
		'split_rules' => [
			'type' => PaymentRequestSplitRule::class.'[]',
			'default' => null,
			'silent' => true,
			'with' => true
		],
		'sender_address' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'sender_city' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'sender_country_code' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'sender_first_name' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'sender_last_name' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'sender_postal_code' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'letter_of_credit' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'letter_of_credit_date' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'subscribe' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'subscribe_date_start' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'subscribe_periodicity' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'customer' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'customer_user_id' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'dae' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'info' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'product_category' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'product_description' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'product_name' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'product_url' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'result_url' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
		'phone' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
	],

	'PaymentRequestSplitRule' => [
		'public_key' => ['type' => 'string'],
		'amount' => ['type' => 'float'],
		'commission_payer' => ['type' => 'string'],
		'server_url' => ['type' => 'string', 'default' => null, 'silent' => true, 'with' => true],
	],

	'PaymentResponse' => [
		'acq_id' => ['type' => 'float', 'default' => null, 'silent' => true],
		'action' => ['type' => 'string', 'default' => null, 'silent' => true],
		'agent_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount_credit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_debit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'commission_credit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'commission_debit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'currency' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_credit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_debit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'is_3ds' => ['type' => 'bool', 'default' => null, 'silent' => true],
		'liq_pay_order_id' => ['type' => 'string', 'default' => null, 'silent' => true, 'alias' => 'liqpay_order_id'],
		'mpi_eci' => ['type' => 'int', 'default' => null, 'silent' => true],
		'order_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'payment_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'public_key' => ['type' => 'string', 'default' => null, 'silent' => true],
		'qr_code' => ['type' => 'string', 'default' => null, 'silent' => true],
		'receiver_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'status' => ['type' => 'string', 'default' => null, 'silent' => true],
		'transaction_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'version' => ['type' => 'float', 'default' => null, 'silent' => true],
	],

	'RefundRequest' => [
		'order_id' => ['type' => 'string', 'with' => true],
		'amount' => ['type' => 'float', 'with' => true],
	],

	'RefundResponse' => [
		'status' => ['type' => 'string'],
		'action' => ['type' => 'string', 'default' => null, 'silent' => true],
		'payment_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'wait_amount' => ['type' => 'bool', 'default' => null, 'silent' => true],
	],

	'StatusRequest' => [
		'order_id' => ['type' => 'string', 'with' => true],
	],

	'StatusResponse' => [
		'status' => ['type' => 'string'],
		'order_id' => ['type' => 'string'],
		'acq_id' => ['type' => 'float', 'default' => null, 'silent' => true],
		'action' => ['type' => 'string', 'default' => null, 'silent' => true],
		'agent_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount_credit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_debit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'auth_code_credit' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'authcode_credit', 'write_as'=> 'authcode_credit',
		],
		'auth_code_debit' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'authcode_debit', 'write_as'=> 'authcode_debit',
		],
		'bonus_percent' => [
			'type' => 'float', 'default' => 0.0, 'silent' => true,
			'read_as'=> 'bonus_procent', 'write_as'=> 'bonus_procent',
		],
		'bonus_type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'card_token' => ['type' => 'string', 'default' => null, 'silent' => true],
		'commission_credit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'commission_debit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'create_date' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_credit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_debit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'end_date' => ['type' => 'string', 'default' => null, 'silent' => true],
		'err_code' => ['type' => 'string', 'default' => null, 'silent' => true],
		'err_description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'info' => ['type' => 'string', 'default' => null, 'silent' => true],
		'ip' => ['type' => 'string', 'default' => null, 'silent' => true],
		'is_3ds' => ['type' => 'bool', 'default' => null, 'silent' => true],
		'liq_pay_order_id' => ['type' => 'string', 'default' => null, 'silent' => true, 'alias' => 'liqpay_order_id'],
		'mpi_eci' => ['type' => 'int', 'default' => null, 'silent' => true],
		'payment_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'pay_type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'public_key' => ['type' => 'string', 'default' => null, 'silent' => true],
		'receiver_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'rrn_credit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'rrn_debit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_card_bank' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_country' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_mask2' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_phone' => ['type' => 'string', 'default' => null, 'silent' => true],
		'transaction_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'version' => ['type' => 'float', 'default' => null, 'silent' => true],
	],

	'CallbackNotification' => [
		'status' => ['type' => 'string'],
		'order_id' => ['type' => 'string'],
		'acq_id' => ['type' => 'float', 'default' => null, 'silent' => true],
		'action' => ['type' => 'string', 'default' => null, 'silent' => true],
		'agent_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'amount_credit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'amount_debit' => ['type' => 'float', 'default' => null, 'silent' => true],
		'auth_code_credit' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'authcode_credit', 'write_as'=> 'authcode_credit',
		],
		'auth_code_debit' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'authcode_debit', 'write_as'=> 'authcode_debit',
		],
		'card_token' => ['type' => 'string', 'default' => null, 'silent' => true],
		'commission_credit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'commission_debit' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'completion_date' => ['type' => 'string', 'default' => null, 'silent' => true],
		'create_date' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_credit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'currency_debit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'customer' => ['type' => 'string', 'default' => null, 'silent' => true],
		'description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'end_date' => ['type' => 'string', 'default' => null, 'silent' => true],
		'err_code' => ['type' => 'string', 'default' => null, 'silent' => true],
		'err_description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'info' => ['type' => 'string', 'default' => null, 'silent' => true],
		'ip' => ['type' => 'string', 'default' => null, 'silent' => true],
		'is_3ds' => ['type' => 'bool', 'default' => null, 'silent' => true],
		'liq_pay_order_id' => ['type' => 'string', 'default' => null, 'silent' => true, 'alias' => 'liqpay_order_id'],
		'mpi_eci' => ['type' => 'int', 'default' => null, 'silent' => true],
		'payment_id' => ['type' => 'string', 'default' => null, 'silent' => true],
		'pay_type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'public_key' => ['type' => 'string', 'default' => null, 'silent' => true],
		'receiver_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'redirect_to' => ['type' => 'string', 'default' => null, 'silent' => true],
		'refund_date_last' => ['type' => 'string', 'default' => null, 'silent' => true],
		'rrn_credit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'rrn_debit' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_bonus' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_card_bank' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_country' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_mask2' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_card_type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_commission' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'sender_first_name' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_last_name' => ['type' => 'string', 'default' => null, 'silent' => true],
		'sender_phone' => ['type' => 'string', 'default' => null, 'silent' => true],
		'token' => ['type' => 'string', 'default' => null, 'silent' => true],
		'type' => ['type' => 'string', 'default' => null, 'silent' => true],
		'version' => ['type' => 'float', 'default' => null, 'silent' => true],
		'err_erc' => ['type' => 'string', 'default' => null, 'silent' => true],
		'product_category' => ['type' => 'string', 'default' => null, 'silent' => true],
		'product_description' => ['type' => 'string', 'default' => null, 'silent' => true],
		'product_name' => ['type' => 'string', 'default' => null, 'silent' => true],
		'product_url' => ['type' => 'string', 'default' => null, 'silent' => true],
		'refund_amount' => ['type' => 'float', 'default' => 0.0, 'silent' => true],
		'verify_code' => [
			'type' => 'string', 'default' => null, 'silent' => true,
			'read_as'=> 'verifycode', 'write_as'=> 'verifycode',
		],
	],

];
